### ISSUE TITLE
Update to Azure AD v2.0?

### ISSUE THREAD

**Issue by DennisPan** [KonaTeam/omniauth-azure-oauth2#10]
Just got some information that Azure AD v2.0 addressed some bugs I'm noticing (e.g. login using a Microsoft id through Azure AD doesn't work, even though the account is in an Azure AD). Any plan to update the code to v2.0? Any objection if I go and attempt to make the update?

**Comment by marknadig** [comment]
hi @DennisPan , no objection. I'm not in a position to test it out right now. So, it may be less friction for you to fiddle with this in your own fork.
