### ISSUE TITLE
Consider 0.0.7 release for current state of master

### ISSUE THREAD

**Issue by martin-paulus** [KonaTeam/omniauth-azure-oauth2#13]
Please consider adding a release tag for the current state of master as of a88593a0f83e2b1864018b891a53830c8b6a4d86.

In my experience while configuring GitLab 8.11.2 from source, the commits after the 0.0.6 release proved essential in getting Azure AD authentication working.

Currently the entry for this gem in my Gemfile looks like this:
gem 'omniauth-azure-oauth2', git: 'https://github.com/KonaTeam/omniauth-azure-oauth2.git', branch: 'master'

Which works fine at this moment, but I would like to fixate the version I am installing.
A new release would simplify the install of the correct version of this gem.

Thank you for maintaining this project in the first place ;)

**Comment by spemmons** [comment]
👍 we've also been using this in our fork (which we would like to remove) to resolve issues working with Azure AD and it's working great. Thanks also for this great gem!

**Comment by marknadig** [comment]
Thanks for all the PRs! Bumped to 0.0.8 just in case and published.
