### ISSUE TITLE
Support for getting fresh access token

### ISSUE THREAD

**Issue by beders** [KonaTeam/omniauth-azure-oauth2#18]
Would be very helpful to have a helper method to use the refresh token to get a fresh access token?
Any guidance on this?

**Comment by marknadig** [comment]
Sorry, I don't. I'm off on other projects, so can't research ATM.

**Comment by MattRyder** [comment]
Argh. Azure tokens are as short-lived as today's memes, and without this functionality it puts a dent into the project's efficacy. Users hate being told to do things, especially to keep logging in.

I've just implemented refreshing the Azure access token myself, with a little help from Google, and I'll leave it here for the next weary traveler who sees this issue, much like I did.

```ruby
       # OAuth2 gem is a dependency of Omniauth, should be immediately available to you
        client = OAuth2::Client.new(
          ENV["AZURE_CLIENT_ID"],
          ENV["AZURE_CLIENT_SECRET"],
          authorize_url: "/common/oauth2/authorize",
          token_url: "/common/oauth2/token",
          site: "https://login.microsoftonline.com",
          resource: "https://analysis.windows.net/powerbi/api")

        access_token = OAuth2::AccessToken.from_hash(client, { refresh_token: self.refresh_token })

        access_token = access_token.refresh!
```
