### ISSUE TITLE
The configuration of "base_azure_url" does not work

### ISSUE THREAD

**Issue by iRockyZhou** [KonaTeam/omniauth-azure-oauth2#19]
## My Config(gitlab.rb)

Is the right configuration correct?
```Ruby
gitlab_rails['omniauth_external_providers'] = ['azure_oauth2']
gitlab_rails['omniauth_providers'] = [
  {
    "name" => "azure_oauth2",
    "args" => { 
      "client_id" => "my client id",
      "client_secret" => "my client secret",
      "tenant_id" => "my tenant id",
      # Note: This is the auth site of China
      "base_azure_url" => "https://login.chinacloudapi.cn",
    },
  }
]
```

## Symptom description

I configured Gitlab-CE in accordance with the above method, and then `sudo gitlab-ctl reconfigure` it.
When I open the landing page again, the Azure AD button appears on the page as shown below.
![sign in page](https://segmentfault.com/img/bVW9MX?w=1097&h=621)
But when I click the Azure AD button, the page to jump to https://login.microsoftonline.com/MyTenantId/oauth2/authorize (see below). It should jump to https://login.chinacloudapi.cn/MyTenantId/oauth2/authorize
![login.microsoftonline.com](https://segmentfault.com/img/bVW3fW?w=858&h=366)

## Uhhh, where is the right place to write?

```Ruby
### OmniAuth Settings
###! Docs: https://docs.gitlab.com/ce/integration/omniauth.html
gitlab_rails['omniauth_enabled'] = true
gitlab_rails['omniauth_allow_single_sign_on'] = ['azure_oauth2']
gitlab_rails['omniauth_sync_email_from_provider'] = 'azure_oauth2'
gitlab_rails['omniauth_sync_profile_from_provider'] = ['azure_oauth2']
gitlab_rails['omniauth_sync_profile_attributes'] = ['email']
# gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'azure_oauth2'
gitlab_rails['omniauth_block_auto_created_users'] = true
gitlab_rails['omniauth_auto_link_ldap_user'] = true
# gitlab_rails['omniauth_auto_link_saml_user'] = false
gitlab_rails['omniauth_external_providers'] = ['azure_oauth2']
gitlab_rails['omniauth_providers'] = [
  {
    "name" => "azure_oauth2",
    "args" => { 
      "client_id" => "My client_id",
      "client_secret" => "My client_secret",
      "tenant_id" => "My tenant_id",
      # Uhhh, where is the right place to write?
      "base_azure_url" => "https://login.chinacloudapi.cn",
    },
    # Uhhh, where is the right place to write?
    "base_azure_url" = "https://login.chinacloudapi.cn"
  }
]
# Uhhh, where is the right place to write?
gitlab_rails['base_azure_url'] = "https://login.chinacloudapi.cn"
# Uhhh, where is the right place to write?
gitlab_rails['omniauth_base_azure_url'] = "https://login.chinacloudapi.cn"
```

## So here comes the question...

Can you tell me how to configure omniauth-azure-oauth2 to jump to https://login.chinacloudapi.cn?

Endless thanks

**Comment by marknadig** [comment]
@marcus-fellinger-esc you're using this w/ gitlab, right? Can you help @iRockyZhou ?
thank you.

**Comment by drhbigdave** [comment]
I am having this exact same issue. On reconfigure I get the following error that documentation informs is a gitlab.rb issue:
Running handlers:
There was an error running gitlab-ctl reconfigure:

undefined method `gitlab' for nil:NilClass

It seems being able to force the base url to the login is critical for the environment I am working in.

Is there any direction on this? I have tried all the tries @iRockyZhou tried.

**Comment by drhbigdave** [comment]
Turns out that when I added base_azure_url it just made gitlab unhappy with the gitlab.rb file altogether and nothing worked. I recreated from a backup copy, added base_azure_url under "args" and it all works swimmingly. Nearly so anyway, still have auth issues, but now I have different auth issues.
