### ISSUE TITLE
Role claims authorization

### ISSUE THREAD

**Issue by kandelchy** [KonaTeam/omniauth-azure-oauth2#21]
So I use this gem to authenticate users and it works just fine. Now I am trying to use Azure to define users/groups roles and did that by editing the app manifest in Azure AD. My question is there a way to include those roles in the access token received by rails app ? I used JWT gem to read the token but it does not include the roles I defined in Azure.

**Comment by marknadig** [comment]
See https://github.com/KonaTeam/omniauth-azure-oauth2/pull/16# if you'd like to pull the salient bits out. That PR's got some problems, but you may be able to extract what you need.
