### ISSUE TITLE
Include tenant id in info?

### ISSUE THREAD

**Issue by DennisPan** [KonaTeam/omniauth-azure-oauth2#8]
Hi,

We've been using the gem for both single tenant and multi tenant applications. For multi tenant, we added strategy to include `tid` in `info`, so that we can use that to query against the specific tenant. I wonder if we should add this in the gem so that everyone get this by default? I can send a pull request if that makes sense.

Thanks!
Dennis

**Comment by marknadig** [comment]
yeah, a PR is fine as long as there are tests. Thanks!

**Comment by DennisPan** [comment]
This is now done: https://github.com/KonaTeam/omniauth-azure-oauth2/commit/ebf9bd993c6e39421d1d1c6453c1444e795e8de5 . Thanks!
